int getCmd(char* buff, char* cmd[]);
void showShell(void);
void getInput(char buff[]);
void myECHO(char text[]);
void myCAT(char *filename);
void myMKDIR(char *dirname);
void myRM(char *filename);
void myCD(char *path);
void myPWD();
void myWC(char *filename);
